-- ============================================================
-- Ejercicio 1 — Empleados contratados después del promedio
-- Consigna:
--   Elaborar una consulta que muestre el listado de empleados
--   cuya fecha de contratación sea posterior al promedio
--   general de fechas de contratación registradas en la empresa.
-- ============================================================

-- ============================================================
-- Ejercicio 2 — Clientes sin pedidos
-- Consigna:
--   Elaborar una consulta que permita identificar los clientes
--   que no hayan realizado ningún pedido en el sistema.
-- ============================================================

-- ============================================================
-- Ejercicio 3 — Empleados con ventas en 2013
-- Consigna:
--   Elaborar una consulta que identifique los empleados
--   que hayan participado en al menos una venta
--   realizada durante el año 2013.
-- Requisito:
--   Debe utilizarse EXISTS.
-- ============================================================

-- ============================================================
-- Ejercicio 4 — Productos más caros que el promedio de su categoría
-- Consigna:
--   Elaborar una consulta que muestre los productos cuyo
--   precio de lista sea superior al promedio de precios
--   de su misma subcategoría.
-- ============================================================

-- ============================================================
-- Ejercicio 5 — Promedio anual de ventas
-- Consigna:
--   Elaborar una consulta que calcule el promedio de ventas
--   por año.
--   Primero se debe obtener el total de ventas por año
--   mediante una subconsulta en el FROM.
-- Entregar:
--   Año y promedio anual de ventas.
-- ============================================================